version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://test:test@mongo:27017/
    depends_on:
      - mongo

  app: 
    build: .
    volumes:
      - ./:/app/
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: yarn start:dev
    env_file:
      - .env
    depends_on:
      - mongo
